const REQUEST_ERROR_CODE = "FF0000"
const REQUEST_ACCESS_ERROR_CODE = "FF0001"


const REQUEST_SUCCESS_CODE = "AA0000"

const REQUEST_SUCCESS_CREATED_CODE = "AA0001"

const REQUEST_SUCCESS_UPDATED_CODE = "AA0002"

const REQUEST_SUCCESS_DELETED_CODE = "AA0003"

const REQUEST_SUCCESS_READ_CODE = "AA0004"


module.exports = {
  REQUEST_ERROR_CODE,
  REQUEST_ACCESS_ERROR_CODE,
  REQUEST_SUCCESS_CODE,
  REQUEST_SUCCESS_CREATED_CODE,
  REQUEST_SUCCESS_UPDATED_CODE,
  REQUEST_SUCCESS_DELETED_CODE,
  REQUEST_SUCCESS_READ_CODE
}
